### ISSUE TITLE
Hi, will there be documentation written for the use of this engine?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [glassesneo/saohime#2]

**Comment by glassesneo** [comment]
Please go see `examples/event.nim` for a minimal example, which just opens a window and wait til the x button is pressed, and then close the window. Also, `example_app/` contains the prototype of a tiny game. you can run it by `nimble runExampleApp`.
All the API around Entity Component System follow [ecslib](https://github.com/glassesneo/ecslib) but please note that soon there will be a big change on the grammar of the system in ecslib. It will probably be after that that I will create the docs.

**Comment by Yakumo-Yukari** [comment]
> Please go see `examples/event.nim` for a minimal example, which just opens a window and wait til the x button is pressed, and then close the window. Also, `example_app/` contains the prototype of a tiny game. you can run it by `nimble runExampleApp`. All the API around Entity Component System follow [ecslib](https://github.com/glassesneo/ecslib) but please note that soon there will be a big change on the grammar of the system in ecslib. It will probably be after that that I will create the docs.

Thank you for sharing this project very cool

**Comment by glassesneo** [comment]
@Yakumo-Yukari 
I have created [API.md](https://github.com/glassesneo/ecslib/blob/develop/docs/API.md) and [system_dsl.md](https://github.com/glassesneo/ecslib/blob/develop/docs/system_dsl.md) for ecslib. In addition, I have also created [docs/API.md](https://github.com/glassesneo/saohime/blob/develop/docs/API.md) in this repo.

Now I'm writing the docs for every default plugin. You can see some of them e.g. [plugins/asset/API.md](https://github.com/glassesneo/saohime/blob/develop/src/saohime/plugins/asset/API.md), [plugins/event/API.md](https://github.com/glassesneo/saohime/blob/develop/src/saohime/plugins/event/API.md)

**Comment by Yakumo-Yukari** [comment]
> @Yakumo-Yukari I have created [API.md](https://github.com/glassesneo/ecslib/blob/develop/docs/API.md) and [system_dsl.md](https://github.com/glassesneo/ecslib/blob/develop/docs/system_dsl.md) for ecslib. In addition, I have also created [docs/API.md](https://github.com/glassesneo/saohime/blob/develop/docs/API.md) in this repo.
> 
> Now I'm writing the docs for every default plugin. You can see some of them e.g. [plugins/asset/API.md](https://github.com/glassesneo/saohime/blob/develop/src/saohime/plugins/asset/API.md), [plugins/event/API.md](https://github.com/glassesneo/saohime/blob/develop/src/saohime/plugins/event/API.md)

thx
